### ISSUE TITLE
chat:user:mute crashes

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-cli#14]
It should ask for two user (ie. Tommaso mutes Jake).

```
Error: StreamChat error code 4: Mute failed with error: "either user or user_id must be provided when using server side auth."
    at StreamChat.errorFromResponse (~/.config/yarn/global/node_modules/stream-chat/dist/index.js:4245:15)
    at StreamChat.handleResponse (~/.config/yarn/global/node_modules/stream-chat/dist/index.js:4259:20)
    at StreamChat._callee8$ (~/.config/yarn/global/node_modules/stream-chat/dist/index.js:4044:56)
    at tryCatch (~/.config/yarn/global/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (~/.config/yarn/global/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as throw] (~/.config/yarn/global/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (~/.config/yarn/global/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _throw (~/.config/yarn/global/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
```

**Comment by nparsons08** [comment]
Resolved in getstream-cli@0.0.53
