### ISSUE TITLE
UpdateUsers failed with error: "api_key is invalid"

### ISSUE THREAD

**Issue by olivermontes** [GetStream/stream-cli#2]
Can't log chats

`
stream chat:log                                                                                                                                                                ✔  5146  18:56:29
✔ What is the unique identifier for the channel? · 1
✔ What type of channel is this? · livestream
✔ What event would you like to filter on? · all
Error: StreamChat error code 2: UpdateUsers failed with error: "api_key is invalid"
    at StreamChat.errorFromResponse (/usr/local/lib/node_modules/getstream-cli/node_modules/stream-chat/dist/index.js:3034:15)
    at StreamChat.handleResponse (/usr/local/lib/node_modules/getstream-cli/node_modules/stream-chat/dist/index.js:3048:20)
    at StreamChat._callee7$ (/usr/local/lib/node_modules/getstream-cli/node_modules/stream-chat/dist/index.js:2896:56)
    at tryCatch (/usr/local/lib/node_modules/getstream-cli/node_modules/stream-chat/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/getstream-cli/node_modules/stream-chat/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/getstream-cli/node_modules/stream-chat/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/usr/local/lib/node_modules/getstream-cli/node_modules/stream-chat/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _throw (/usr/local/lib/node_modules/getstream-cli/node_modules/stream-chat/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
`

**Comment by nparsons08** [comment]
Hi @olivermontes, did you run `stream config:set` prior to your command? Either that wasn't set properly, or the Stream `apiKey` is in fact invalid. Thank you for reporting!
